parameters:
    env(DEFAULT_LOCAL): 'en'
    env(HTTP_CLIENT_MAX_CONNECTIONS): 4
    env(ELASTICMS_PATH): '%kernel.project_dir%/vendor/elasticms'

framework:
    default_locale: '%env(DEFAULT_LOCAL)%'
    http_method_override: false
    handle_all_throwables: true
    secret: '%env(APP_SECRET)%'

    http_client:
        max_host_connections: '%env(int:HTTP_CLIENT_MAX_CONNECTIONS)%'

    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: strict
        storage_factory_id: session.storage.factory.native

    esi: true
    fragments: true
    php_errors:
        log: true

    validation:
        email_validation_mode: html5

when@redis:
    framework:
        session:
            handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler

when@db:
    framework:
        session:
            handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler

when@store_data:
    framework:
        session:
            handler_id: ems_common.store_data_session_handler

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
